const typeDefs = `
scalar DateTime

type Message {
    id: ID!
    content: String!
    writtenBy: String
    email: String!
    createdAt: DateTime!
    updatedAt: DateTime!
    approvedAt: DateTime
}

type AddMessageResponse {
    code: String!
}

type MessageApprovalResponse {
    approved: Boolean!
}

type MessageApproval {
    id: ID!
    code: String!
    message: Message
    createdAt: DateTime!
    updatedAt: DateTime!
    approvedAt: DateTime
}

type Query {
    messages: [Message]
}

input AddMessageInput {
    content: String!
    writtenBy: String
    email: String!
}

input MessageApprovalInput {
    approvalId: String!
    test: Boolean
}

type Mutation {
    approveMessage(input: MessageApprovalInput!): MessageApprovalResponse!
    addMessage(input: AddMessageInput!): AddMessageResponse!
}

`;

module.exports = typeDefs;